site_name: Sistemas Operativos en Red
site_url: https://lupastance.github.io/sistemas-operativos-en-red

theme:
  name: material
  language: es
  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    - scheme: slate
      primary: amber
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

    - scheme: default
      primary: light blue
      accent: red
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

  plugins:
    - offline
    - open-in-new-tab
    - search:
      enabled: true
      lang: es

  features:
    - header.autohide
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra:
  home: https://lupastance.github.io/interfaces/
  generator: false
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/Rdyt6kvJAq
      name: Únete al canal de Discord

copyright: Copyright &copy; Luis Alemañ 2024